print("Tutorial como lavar los platos:")
print("Necesitaras: ")
print("1. Platos sucios")
print("2. Esponja")
print("3. Detergente")
print("4. Virutilla de platos")
print("5. Secador")
print("Procedimiento:")
print("1. En primer lugar necesitaras los platos sucios, estos deben encontrarse en tu fregadero, posteriormente llenolos de agua")
print("2. utiliza la esponja para remojar con agua y ponle una gota de detergente y empieza a pasar por todos los platos sucios")
print("3. Si ves que la suciedad se resiste a salir, utiliza la virutilla para raspar esos lugares muy sucios pero ten cuidado en no raspar demasiado")
print("4. Una vez pasada y retirada la suciedad vuelva a pasar los platos por agua para un ultimo lavado")
print("5. Utiliza el secador para quitar el exceso de aguar, y deja los platos en un lugar seco para que el agua restante se evapore")
print("Platos Limpios!!")